version: "3.7"

services:
  islb:
    image: pionwebrtc/ion:latest-islb
    build:
      dockerfile: ./docker/islb.Dockerfile
      context: .
    volumes:
      - "./configs/docker/islb.toml:/configs/islb.toml"
    depends_on:
      - nats
      - redis
    networks:
      - ionnet

  sfu:
    image: pionwebrtc/ion:latest-sfu
    build:
      dockerfile: ./docker/sfu.Dockerfile
      context: .
    volumes:
      - "./configs/docker/sfu.toml:/configs/sfu.toml"
    ports:
      - "5000-5200:5000-5200/udp"
    depends_on:
      - nats
    networks:
      - ionnet

  avp:
    image: pionwebrtc/ion:latest-avp
    build:
      dockerfile: ./docker/avp.Dockerfile
      context: .
    volumes:
      - "./configs/docker/avp.toml:/configs/avp.toml"
      - "./out:/out/"
    depends_on:
      - nats
    networks:
      - ionnet

  biz:
    image: pionwebrtc/ion:latest-biz
    build:
      dockerfile: ./docker/biz.Dockerfile
      context: .
    volumes:
      - "./configs/docker/biz.toml:/configs/biz.toml"
    ports:
      - 8443:8443
    depends_on:
      - nats
    networks:
      - ionnet

  nats:
    image: nats
    ports:
      - 4222:4222
    networks:
      - ionnet

  redis:
    image: redis:6.0.9
    ports:
      - 6379:6379
    networks:
      - ionnet

networks:
  ionnet:
    external: true
    name: ionnet
    driver: bridge
