[global]
pprof = ":6062"

# data center id
dc = "dc1"

[webrtc]
# ice = ["stun:stun.l.google.com:19302"]

[rtp]
# listen port
port = 6667

[log]
level = "info"
# level = "debug"

[etcd]
# ["ip:port", "ip:port"]
addrs = ["etcd:2379"]

[nats]
url = "nats://nats:4222"

[avp]
[avp.processors.recorder]
dest = "gcloud"
bucket = "stream-storage-inside-iq"
[avp.processors.recorder.audio]
sampling = 48000
channels = 2

[avp.processors.speech]
sampling = 48000
channels = 1
streaminglimit = 240000