[global]
pprof = ":6060"
# data center id
dc = "dc1"

[log]
level = "info"
# level = "debug"

[nats]
url = "nats://127.0.0.1:4222"

[node]
# node id
nid = "biz01"

[redis]
addrs = [":6379"]
password = ""
db = 0
